# Generated by Django 2.2 on 2019-07-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190705_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='store.Order'),
        ),
    ]
