# Generated by Django 2.2.2 on 2019-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uploader', models.CharField(max_length=64)),
                ('body', models.FileField(upload_to='images/')),
            ],
        ),
    ]
