# Generated by Django 2.2.2 on 2019-06-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='body',
            new_name='file',
        ),
    ]
